---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    ci_cd_namespace: labs-ci-cd
    dev_namespace: labs-dev
    test_namespace: labs-test
    set_admin: false
  roles:
    - { role: openshift-applier/roles/openshift-applier }
    - { role: configure-nexus }
