---

ansible_connection: local

openshift_cluster_content:
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params: "{{ playbook_dir }}/params/projectrequests/ci-cd"
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params: "{{ playbook_dir }}/params/projectrequests/dev"
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params: "{{ playbook_dir }}/params/projectrequests/test"
    tags:
    - projects
- object: group-role-binding
  content:
  - name: "ci-cd-acl-edit"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/edit"
    tags:
    - rolebinding-group
  - name: "labs-dev-acl-edit"
    namespace: "{{ dev_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/edit"
    tags:
    - rolebinding-group
  - name: "labs-test-acl-edit"
    namespace: "{{ test_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/edit"
    tags:
    - rolebinding-group
  - name: "ci-cd-acl-admin"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/admin"
    tags:
    - rolebinding-group
  - name: "labs-dev-acl-admin"
    namespace: "{{ dev_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/admin"
    tags:
    - rolebinding-group
  - name: "labs-test-acl-admin"
    namespace: "{{ test_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/admin"
    tags:
    - rolebinding-group