---
- name: "Look up Nexus Password"
  command: >
    oc get secret nexus-password -o custom-columns=SECRET:.data.password --no-headers | base64 --decode
  register: new_nexus_password_result

- name: "Set new_nexus_password Result"
  set_fact:
    new_nexus_password: "{{ new_nexus_password_result.stdout }}"
  when:
  - new_nexus_password is not defined or new_nexus_password|trim == ''

- name: "Configure Admin Password"
  include_tasks: configure-repos.yml
  with_items:
  - "{{ admin_setup | default([]) }}"