---

- name: "Look up Nexus URL"
  command: >
    oc get route {{ nexus_name | default('nexus') }} -n {{ content.namespace }} -o custom-columns=ROUTE:.spec.host --no-headers
  register: nexus_url_result
  when:
  - nexus_url is not defined or nexus_url|trim == ''

- name: "Set nexus_url Result"
  set_fact:
    nexus_url: "{{ nexus_url_result.stdout }}"
  when:
  - nexus_url is not defined or nexus_url|trim == ''

- name: "Look up Nexus Password"
  command: >
    oc get secret nexus-password -o custom-columns=SECRET:.data.password --no-headers | base64 --decode
  register: new_nexus_password_result

- name: "Set new_nexus_password Result"
  set_fact:
    new_nexus_password: "{{ new_nexus_password_result.stdout }}"
  when:
  - new_nexus_password is not defined or new_nexus_password|trim == ''

- name: "Ensure Nexus is available before attempting to communicate"
  include_tasks: wait-for-nexus.yml

- name: "Configure Repos"
  include_tasks: configure-repos.yml
  with_items:
  - "{{ nexus_repos | default([]) }}"

- name: "Configure Admin Password with {{ new_nexus_password }}"
  include_tasks: configure-repos.yml
  with_items:
  - "{{ admin_setup | default([]) }}"