apiVersion: v1
kind: Template
labels:
  template: source-secret
metadata:
  name: source-secret
objects:
- apiVersion: v1
  stringData:
    password: ${PASSWORD}
    username: ${USERNAME}
  kind: Secret
  metadata:
    labels:
      credential.sync.jenkins.openshift.io: true
    name: ${SECRET_NAME}
    type: kubernetes.io/basic-auth
parameters:
- description: The password for jenkins's to access git repos
  displayName: Jenkins service password in gitland
  name: PASSWORD
  value: jenkins
- description: The username for jenkins's to access git repos
  displayName: Jenkins service username in gitland
  name: USERNAME
  value: jenkins
- description: The name for the newly created secret
  displayName: Secret name
  name: SECRET_NAME
  value: jenkins-git-creds
